version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    working_dir: /app/apps/api
    command: pnpm dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://admin:password@db:5432/monorepo
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    working_dir: /app/apps/web
    command: pnpm dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    working_dir: /app/apps/worker
    command: pnpm dev
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: monorepo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
